### ISSUE TITLE
FR6. Send Notifications when the Profile is Matched.

### ISSUE THREAD

**Issue by gw5045** [WSU-4110/SoulMatch#2]
|FR6. Send notifications when the profile is matched.|
|---|
|**Goal**: To ensure that users are notified when their profile is matched with another user.
**Stakeholders:** Server|
| **Description:** This functional requirement is necessary to ensure that users are notified when their profile is matched with another user, which will inform the user that their attention is needed in the app. |
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |  
|**Date:** 01/28/2023  
|  **Priority:** 3 |

**Comment by Ani180685** [comment]
completed the chat page, but could not implement the notification
